image:
- Ubuntu
- Visual Studio 2017
- macOS


for:
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - mkdir _build
    - cd _build
    - cmake ..
    - cmake --build .

  test_script:
    - ctest --output-on-failure .

-
  matrix:
    only:
      - image: Visual Studio 2017

  install:
    - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\Program Files (x86)\CMake\bin
    - mkdir _build
    - cd _build
    - cmake .. -G "MinGW Makefiles"
    - cmake --build .

  test_script:
    - ctest --output-on-failure .

-
  matrix:
    only:
      - image: macOS

  install:
    - brew install gcc
    - mkdir _build
    - cd _build
    - cmake ..
    - cmake --build .

  test_script:
    - ctest --output-on-failure .

build: off


